# Generated by Django 4.1 on 2023-11-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_fotogradi',
            new_name='data_fotografia',
        ),
    ]
